Test_Login/Controllers/stocksController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Test_Login;
using Test_Login.Models;

namespace GoldRush.Controllers
{
    public class stocksController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private LabEntities db = new LabEntities();
        // GET: stocks
        public ActionResult Index()
        {
            // return View(db.stockPrice.ToList());
            int i = 0;
            return View();
        }


        public ActionResult Chart(string id)
        {

            //var q = db.stockPrice.Select(x => x.stockID + x.stockName).Distinct().OrderBy(x => x).ToList();
            //ViewBag.stockID = q;
            if (id == null)
            {
                return View("Index");
            }
            else
            {
                var stock = db.stockPrice.Where(x => x.stockID == id).OrderBy(x => x.stockDate).ToList();
                if (stock.Count != 0)
                {
                    ViewBag.id = stock.First().stockName + "(" + stock.First().stockID + ")";
                    ViewBag.stockID = stock.First().stockID;
                }
                return View(stock);
            }
        }

        //[HttpPost]
        //public ActionResult Chart(string stockID, string id)
        //{
        //    if (stockID == "")
        //    {
        //        return View("Index");
        //    }
        //    else
        //    {
        //        var stock = db.stockPrice.Where(x => x.stockID == stockID || x.stockName == stockID).OrderBy(x => x.stockDate).ToList();
        //        if (stock.Count != 0)
        //        {
        //            ViewBag.id = stock.First().stockName + "(" + stock.First().stockID + ")";
        //            ViewBag.stockID = stock.First().stockID;
        //        }
        //        return View(stock);
        //    }
        //}

        [HttpPost]
        public async Task<string> Chart(bool isLike, string stockID)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (isLike)
            {
                user.StockBag += stockID + " ";
                #region 寄信用戶感興趣的個股
                string[] stockIDsplit = user.StockBag.Split(' ');
                string userInterestHint = "提供您感興趣的個股，在鉅亨網查詢如下：<br>";
                string userInterest = "";
                int sendMail = 0;
                foreach (string x in stockIDsplit)
                {
                    if (x.Length != 0)
                    {
                        var temp = db.stockPrice.Where(y => y.stockID == x).Select(y => y.stockID + " " + y.stockName).ToList().First();
                        userInterest += $"{temp}：https://www.cnyes.com/search/news?keyword={x}<br>";
                        sendMail = 1;
                    }
                }
                if (sendMail > 0)
                {
                    MailMessage mail = new MailMessage();
                    //前面是發信email後面是顯示的名稱
                    mail.From = new MailAddress("msit38lin@gmail.com", "Gold Rush");

                    //收信者email
                    mail.To.Add(user.Email);

                    //設定優先權
                    mail.Priority = MailPriority.Normal;

                    //標題
                    mail.Subject = "Gold Rush有一些你關心的個股資訊連結";

                    //內容
                    mail.Body = userInterestHint + userInterest;

                    //內容使用html
                    mail.IsBodyHtml = true;

                    //設定gmail的smtp (這是google的)
                    SmtpClient MySmtp = new SmtpClient("smtp.gmail.com", 587);

                    //您在gmail的帳號密碼
                    MySmtp.Credentials = new System.Net.NetworkCredential("msit38lin@gmail.com", "msit3820220308");

                    //開啟ssl
                    MySmtp.EnableSsl = true;

                    //發送郵件
                    MySmtp.Send(mail);

                    //放掉宣告出來的MySmtp
                    MySmtp = null;

                    //放掉宣告出來的mail
                    mail.Dispose();
                    //string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    //await UserManager.SendEmailAsync(user.Id, "2345", "寄信測試2");
                }

                #endregion
            }
            else
            {
                user.StockBag = user.StockBag.Replace(stockID, "");
            }



            await UserManager.UpdateAsync(user);
            return "";
        }


        public ActionResult Strategy(string str)
        {
            // StockPrice的StockDate倒著排
            var dateList = db.stockPrice.OrderByDescending(x => x.stockDate).Select(x => x.stockDate).ToList().Distinct();

            SqlConnection cn = new SqlConnection(@"Data Source=.;Initial Catalog=Lab;Integrated Security=True");
            //string id = "Strategy";
            //string stringID = "";
            string stockArray = "";
            int selectResultcount = 0;

            #region 資料庫末5筆日期(已不需要)
            // 取得資料庫最後5筆日期, 反著讀取依序加入dayList
            //方法1
            //SqlCommand getLast5Day = new SqlCommand();
            //getLast5Day.Connection = cn;
            //getLast5Day.CommandText = "select distinct top(5) stock_date from buy_and_sell_report order by stock_date desc ";
            //cn.Open();
            //SqlDataReader dayResult = getLast5Day.ExecuteReader();
            //List<string> dayList = new List<string>();
            //while (dayResult.Read()) { dayList.Add(Convert.ToString(dayResult[0])); }
            //cn.Close();

            //方法2
            //List<string> dayList = new List<string>();
            //for (int i = 0; i < 5; i++)
            //{
            //    dayList.Add(dateList.ElementAt(i));
            //}
            #endregion
            switch (str)
            {
                case "成交爆大量":
                    //foreach (string s in db.stockPrice.Select(x => x.stockID).Distinct().OrderBy(x => x))
                    //{
                    //    var dbs = db.stockPrice.Where(x => x.stockID == s).ToList();
                    //    try
                    //    {
                    //        if (float.Parse(dbs.Where(x => x.stockDate == "20210409").Select(x => x.endPrice).ToList()[0]) > 900)
                    //        {
                    //            stockArray = stockArray + s + " ";
                    //        }
                    //    }
                    //    catch
                    //    {
                    //    }
                    //}
                    foreach (string s in db.stockPrice.Select(x => x.stockID).Distinct().OrderBy(x => x))
                    {
                        var dbs = db.stockPrice.Where(x => x.stockID == s).OrderByDescending(x => x.stockDate).Take(6).ToList();
                        try
                        {
                            if (dbs[0].numOfSharesTrade > dbs.GetRange(1, 5).Select(x => x.numOfSharesTrade).Sum())
                            {
                                stockArray += s + ", ";
                            }
                        }
                        catch
                        {
                        }
                    }
                    break;
                case "四海遊龍":
                    var db2 = db.stockPrice.Where(x => x.stockID == "2330").OrderByDescending(x => x.stockDate).ToList();
                    double sma5 = db2.GetRange(1, 5).Select(x => Convert.ToDouble(x.endPrice)).Average();
                    double sma10 = db2.GetRange(1, 10).Select(x => Convert.ToDouble(x.endPrice)).Average();
                    double sma20 = db2.GetRange(1, 20).Select(x => Convert.ToDouble(x.endPrice)).Average();
                    double sma60 = db2.GetRange(1, 60).Select(x => Convert.ToDouble(x.endPrice)).Average();
                    double[] sma = new double[] { sma5, sma10, sma20, sma60 };

                    if (double.Parse(db2[0].endPrice) > sma.Max())
                    {
                        stockArray += ", 2330";
                    }
                    stockArray += ", 0050";
                    stockArray += ", 2603";
                    break;
                case "強勢股票":
                    // Convert.ToDouble??
                    var db3 = db.stockPrice.Where(x => x.stockDate == "20220210").ToList();
                    var dbs_Top10 = db3.Select(x => new { date = x.stockID, value = (Convert.ToDouble(x.endPrice) - Convert.ToDouble(x.openPrice)) }).OrderByDescending(x => x.value).ToList();
                    stockArray += ", 2609";
                    stockArray += ", 2409";
                    break;

                case "外資連買":
                    #region 外資查詢連買結果
                    using (SqlCommand getStockID = new SqlCommand())
                    {
                        getStockID.Connection = cn;
                        cn.Open();
                        getStockID.CommandText = "select StockCode, count(StockCode) as countres " +
                            "from buy_and_sell_report " +
                            "Where globalCompany > 500000 " +

Test_Login/Views/Shared/_LayoutRight.cshtml
@using Test_Login.Models.Extensions;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gold Rush</title>
    <link rel="icon" href="~/img/logo2.png" />
    <link rel="stylesheet" href="~/Content/vendor.css">
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/animateCss.css">
    <link rel="stylesheet" href="~/fonts/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="~/assets/custom.css">
    <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css">
    <script href="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <style>
        html, body {
            height: 100%;
            /* background-color: azure; */
        }

        df-messenger {
            --df-messenger-bot-message: #878fac;
            --df-messenger-button-titlebar-color: #fdb813;
            --df-messenger-chat-background-color: #fafafa;
            --df-messenger-font-color: white;
            --df-messenger-send-icon: #878fac;
            --df-messenger-user-message: #479b3d;
        }

        .Table1 {
            position: absolute;
            background-color: white;
            left: 0;
            width: 215px;
            border: solid 1px #e0e0e0;
        }

            .Table1 td {
                height: 0.6rem;
                padding-left: 15px;
            }
        /*條件搜尋*/
        .rightbar {
            position: fixed;
            top: 330px;
            right: 40px;
            box-shadow: 1px 1px 9px 1px #A6A6A6;
            -webkit-box-shadow: 1px 1px 9px 1px #A6A6A6;
            -moz-box-shadow: 1px 1px 9px 1px #A6A6A6;
            -o-box-shadow: 1px 1px 9px 1px #A6A6A6;
        }
    </style>

</head>
<body>

    <div id="page-start-anchor"></div>
    <section class="header header-fixed-xl">
        <div class="header-top-line bg-cyan">
            @*上方Navbar(綠色)欄位*@
            <div class="container">
                <div class="row">

                    <nav class="navbar navbar-expand navbar-dark navbar-short justify-content-end w-100">
                        <ul class="navbar-nav">
                            <li class="nav-item  ">
                                <a class="nav-link text-white justify-content-md-between" href="https://demo.htmlhunters.com/profi/documentation/getting-started/customizing.html">
                                    <span class="text-uppercase" style="color: #17a2b8">
                                        LayoutDemo
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="navbar-spacer"></div>
                        @Html.Partial("_LoginPartial")
                    </nav>
                </div>
            </div>
        </div>
        <div class="header-main bg-white">
            <div class="container" style="max-width:1400px;">
                <div class="row" style="max-width:1400px;">
                    <nav class="navbar navbar-expand-lg navbar-light" id="header-navbar" style="font-size:15px;">
                        @*Navbar(白色)*@
                        <a class="navbar-brand font-weight-bold" href="/Home/Index"><img src="~/img/LOgo.png" style="width: 200px;" /></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <div class="navbar-spacer"></div>
                            <div class="navbar-spacer"></div>
                            <ul class="navbar-nav ml-auto">



                                <li class="nav-item">
                                    <a class="nav-link text-uppercase " data-toggle="none" href="/stocks/Strategy">
                                        挖掘股票
                                    </a>
                                </li>
                                <li class="nav-item">
                                    @if (User.Identity.GetUserTier().ToLower() == "true")
                                    {
                                        <a class="nav-link text-uppercase " data-toggle="none" href="/stocks/Customize">
                                            自訂策略
                                        </a>
                                    }
                                    else
                                    {<a class="nav-link text-uppercase " data-toggle="none" href="/Manage/Pay">
                                            <img src="~/img/lock-removebg-preview.png" width="10" height="10" /> 自訂策略
                                        </a>
                                    }
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-uppercase " data-toggle="none" href="/BackTesting/BackTesting001">
                                        回測:
                                        定期定額(定股)
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-uppercase " data-toggle="none" href="/Home/Message">
                                        討論區
                                    </a>

                                </li>
                            </ul>
                            <div class="navbar-spacer"></div>
                            <a class="btn btn-outline-warning text-uppercase" href="/stocks/Strategy" data-toggle="none" target="">
                                開始發掘
                            </a>

                            <div class="navbar-spacer"></div>
                            <div class="navbar-spacer"></div>

                            @{
                                try
                                {
                                    @Html.Action("SearchBox", "Home")
                                    @*<form>
                                            <section class="search" id="search1">
                                                <div class="row">
                                                    <input type="text" onkeyup="tipBox(this)" class="form-control-sm mb-3 " autocomplete="off" aria-label="search" id="selectStock" placeholder="股票代碼..." aria-invalid="false" value="" />
                                                    <button id="GoToChart" style="border:0px; background-color:white;">
                                                        <i class="material-icons" aria-hidden="true">search </i>
                                                    </button>
                                                </div>
                                            </section>
                                        </form>*@
                                }
                                catch (Exception)
                                {

                                }
                            }

                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    @RenderBody()
    @*<div class="container">
        <div class="row">
            <div>

            </div>
        </div>
    </div>*@
    <div class="rightbar  animated fadeInRight">
        @Html.Action("rightBar", "stocks")
    </div>


    @*footer*@
    <df-messenger intent="WELCOME"
                  chat-title="GoldRushBot"
                  chat-icon="https://i.imgur.com/VSmAgpd.png"
                  agent-id="c7e2956c-5b2c-424f-b914-590a1b66ce19"
                  wait-open="true"
                  language-code="zh-tw">

    </df-messenger>

    <section class="footer bg-cyan-30" style=" width: 100%; position:relative; bottom:0; top:30%">
        <div class="container py-19 py-sm-23 py-lg-25">
            <div class="row align-items-center">
                <div class="col-12 col-md-6 col-lg-5 mb-14 mb-md-0">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-start">
                        <a href="index.html" class="footer-brand">GoldRush</a>
                        <div class="brand-icons-list ml-10 ml-sm-20">
                            <a href="#" class="brand-icon brand-icon-circle brand-icon-facebook">
                                <i class="fa fa-facebook-f"></i>
                            </a>
                            <a href="#" class="brand-icon brand-icon-circle brand-icon-twitter">
                                <i class="fa fa-twitter "></i>
                            </a>
                            <a href="#" class="brand-icon brand-icon-circle brand-icon-pinterest">
                                <i class="fa fa-pinterest-p"></i>
                            </a>

                        </div>

                    </div>
                </div>


                <div class="col-12 col-lg-2 text-center d-none d-lg-block">
                    <a href="#" data-toggle="smooth-scroll" data-target="#page-start-anchor">
                        <i class="material-icons text-black">arrow_upward</i>

                    </a>

                </div>


                <div class="col-12 col-md-6 col-lg-5 text-center text-md-right">
                    <ul class="footer-menu">
                        <li><a href="#" data-toggle="smooth-scroll">聯絡我們</a></li>
                        <li><a href="#"></a></li>
                    </ul>
                </div>
            </div>
           
            <small class="fs-1 font-family-secondary text-uppercase font-weight-bold letter-spacing-caption text-muted" style="margin:0px -10px 0px -10px;">
                免責聲明: 僅提供之分析資料、選股工具僅供參考，不暗示買賣建議，本站對資訊正確、更新延誤或傳輸中斷不負任何責任，依本站資訊交易發生損失需自行負責，請謹慎評估風險。
            </small>
        </div>
    </section>

    <script src="~/Scripts/vendor.js"></script>
    <script src="~/Scripts/app.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>